### ISSUE TITLE
SelfContributors.java:45-46: Implement paging mechanism...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-storage#116]
The puzzle `113-bfd58bbd` from #113 has to be resolved: 

https://github.com/self-xdsd/self-storage/blob/0a6515c33eeb1f1a374c721def1b4f2ecc9023e3/src/main/java/com/selfxdsd/storage/SelfContributors.java#L45-L46

The puzzle was created by @amihaiemil on 25-Aug-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske Can you please take care of this when you have some time? We need to adapt SelfContributors to the new paging mechanism, I guess similarly to how SelfProjects was adapted.

**Comment by criske** [comment]
@amihaiemil sure

**Comment by amihaiemil** [comment]
paid with transaction id 5J1970395V509303G

**Comment by 0pdd** [comment]
The puzzle `113-bfd58bbd` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
