### ISSUE TITLE
SelfProject should use current page when doing queries.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-storage#119]
Right now all queries are relative to whole table.

For example `projects().page(2, 10).ownedBy(user)` => should read as "find all projects owned by user on page 2".
but the actual implementation is searching the whole table as in using `Page.all()` ( `projects().ownedBy(user)`)

Though there is paging done in filter implementation, but those are doing "subpaging" basically.
Using the above example:
`projects().page(2, 10).ownedBy(user).page(1, 2)` => should read as "find all projects owned by user on page 2 then on that result apply page 1 of 2".

Also `SelfProject` should use `Page.all()` in default constructor to avoid confusion. If client will need paging, they will call `projects.page(...)`

**Comment by criske** [comment]
@amihaiemil I'll work on this bug, no bounty needed, PR will be short.

**Comment by amihaiemil** [comment]
@criske sure, thanks, go ahead :D

**Comment by amihaiemil** [comment]
@criske was this fixed already [here](https://github.com/self-xdsd/self-storage/pull/118)?

**Comment by criske** [comment]
@amihaiemil nope I've messed last night the commit message. I've fixed that in the meantime

**Comment by criske** [comment]
@amihaiemil About this issue, the bug is fixed, but without a proper testing I don't want create a pr.
And here is the problem. The projects from from sql test file, are listed apparently in random order (maybe by some internal index key generated when composing PRIMARY KEY (repo_fullname, provider)) .
Order of insert is:
- 'amihaiemil/docker-java-api','github'
- 'amihaiemil/amihaiemil.github.io', 'github'
- 'vlad/test', 'github'
- 'mihai/test', 'gitlab'
But select order is:
- vlad/test : github
- amihaiemil/docker-java-api : github
- amihaiemil/amihaiemil.github.io : github
- mihai/test : gitlab
Should we have at least some creation date field to order by latest or something?

**Comment by amihaiemil** [comment]
@criske 

>  I've messed last night

Never work at night :D 

About the order: why is the order important? For example, you can take Page 2, iterate over all of them and see which one belong to the ``user``, then filter the same instance of Page 2 and see that the result contains only the ones owned by ``user``. 

Or am I missing something?

**Comment by criske** [comment]
@amihaiemil Just for better control when testing with bigger data sets of projects.
But I guess I can test pages having in mind the `select all ` result of 'insertTestData.sql'; I think it will be enough .
