### ISSUE TITLE
Implement SelfUsers.signUp

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-storage#12]
First, check if the User already exists in the DB. 

If he exists, verify if the e-mail address or the access_token have changed -- if there are differences, then perform an UPDATE and return the User.

If he doesn't exist INSERT and return.

Don't forget about tests. You can leave a puzzle for testing in a future task.

**Comment by amihaiemil** [comment]
@criske Wanna try this one? It's an easy starting-point to see how JOOQ works. Testing framework is also already setup :D

**Comment by criske** [comment]
Sure, I've played with jooq before :)
