### ISSUE TITLE
Bug when creating tables in MySql 8.0.21

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-storage#121]
When running `createDb.sql` I'm getting:

`Error Code: 1822. Failed to add the foreign key constraint. Missing index for constraint 'assignee' in the referenced table 'slf_contracts_xdsd'`

Fix: must keep the exact order of `slf_contracts_xdsd` PRIMARY KEY fields when referencing in `slf_tasks_xdsd`

Should look like:
```
CONSTRAINT assignee
    FOREIGN KEY (repo_fullname, provider, role, username)
    REFERENCES self_xdsd.slf_contracts_xdsd (repo_fullname, username, provider, role),
```

where 'slf_contracts_xdsd` has pk declared as:
```
 PRIMARY KEY (repo_fullname, username, provider, role),
```

**Comment by amihaiemil** [comment]
@criske so this is smth that can be fixed in the createDb.sql script, right?

**Comment by criske** [comment]
@amihaiemil yeah, pretty much :)

**Comment by amihaiemil** [comment]
paid with transaction id 57Y28313YB073744C

**Comment by criske** [comment]
safe to close
