### ISSUE TITLE
SelfContributors.java:46-47: Implement method...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-storage#154]
The puzzle `151-3db732a6` from #151 has to be resolved: 

https://github.com/self-xdsd/self-storage/blob/db053b0a4a4972b32802cccd0705ac93aeb97262/src/main/java/com/selfxdsd/storage/SelfContributors.java#L46-L47

The puzzle was created by @amihaiemil on 02-Oct-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I'm the Project Manager of this project. I take care of Issues' assignments, payments and more.Want me to work for your project too? Go [here](https://self-xdsd.com). 

I work primarily at Github, but I'll also start working at GitLab and BitBucket soon.

**Comment by amihaiemil** [comment]
@charlesmike register this issue as a task, please

**Comment by charlesmike** [comment]
> @charlesmike register this issue as a task, please

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-13T14:59:52.088483``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by criske** [comment]
@charlesmike throw a status at me please

**Comment by charlesmike** [comment]
> @charlesmike throw a status at me please

@criske this ticket is assigned to @criske since ``2020-10-03T14:59:52`` and it should be closeduntil ``2020-10-13T14:59:52``. Estimation is ``60`` minutes.

**Comment by amihaiemil** [comment]
paid with transaction id 9UN248506L6068707

**Comment by 0pdd** [comment]
The puzzle `151-3db732a6` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
