### ISSUE TITLE
SelfWallets.java:44-46: Implement and test method...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-storage#162]
The puzzle `160-754150d0` from #160 has to be resolved: 

https://github.com/self-xdsd/self-storage/blob/d14d217389664c14c9bfbad8ec4f1468ca428d94/src/main/java/com/selfxdsd/storage/SelfWallets.java#L44-L46

The puzzle was created by @amihaiemil on 17-Oct-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@charlesmike please pay attention to this new issue.

**Comment by charlesmike** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-27T12:59:50.772776``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
paid with transaction id 0RL499365E510221D

**Comment by 0pdd** [comment]
The puzzle `160-754150d0` has disappeared from the source code, that's why I closed this issue. //cc @charlesmike

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
