### ISSUE TITLE
SelfPaymentMethods.java:47-48: Continue implementing the...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-storage#165]
The puzzle `163-4c2bfb7b` from #163 has to be resolved: 

https://github.com/self-xdsd/self-storage/blob/92cc717a61491282f0c573f5d589b2fa487ca708/src/main/java/com/selfxdsd/storage/SelfPaymentMethods.java#L47-L48

The puzzle was created by @amihaiemil on 17-Oct-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@charlesmike please pay attention to this new issue.

**Comment by charlesmike** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0pdd** [comment]
> @0pdd thank you for reporting this. I'll assign someone to take care of it soon.

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-27T14:49:50.777159``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@criske I will take care of this

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.

**Comment by 0pdd** [comment]
The puzzle `163-4c2bfb7b` has disappeared from the source code, that's why I closed this issue. //cc @charlesmike
