### ISSUE TITLE
Release 0.0.25/Update to self-core 0.0.55

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-storage#222]
Some small changes needed, then we release 0.0.25

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-30T10:46:15.393790``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.25`

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
