### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-storage#231]
After DB changes.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-07T13:04:02.708830``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike resign

**Comment by charlesmike** [comment]
> @charlesmike resign

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by amihaiemil** [comment]
@charlesmike remove

**Comment by charlesmike** [comment]
> @charlesmike remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
