### ISSUE TITLE
SelfPms.java:38-39: Implement a paging mechanism in...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-storage#26]
The puzzle `20-7df03c6b` from #20 has to be resolved: 

https://github.com/self-xdsd/self-storage/blob/939f6a024ccfc3afe02194e869f93fb4e4deed1c/src/main/java/com/selfxdsd/storage/SelfPms.java#L38-L39

The puzzle was created by cristianpela on 02-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll take this

**Comment by amihaiemil** [comment]
@criske Don't write too much code. It's ok to start with a small PR so we can see the overall idea first.

**Comment by 0pdd** [comment]
The puzzle `20-7df03c6b` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
