### ISSUE TITLE
SelfInvoices.java: Remove the DB columns Invoice... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-storage#268]
The puzzle ``1627036395`` originating from #264 has to be resolved:

https://github.com/self-xdsd/self-storage/blob/7bcb78d819ecfa1724a8092aae9d430802e52dc2/src/main/java/com/selfxdsd/storage/SelfInvoices.java#L48-L50

"Remove the DB columns Invoice.transactionId and timestamp. They should be read from the successful Payment, if it exists. When reading an Invoice, we should LEFT JOIN with Payments on the id and status SUCCESS.".

The puzzle was created by @amihaiemil at ``2021-03-07 15:16:35 +0200``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-17T13:27:25.243262``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
Change: we will always read the ``latest`` Payment of the Invoice, not just the SUCCESS one. This is because we need to show the payment status (of the last payment) to the users on the UI in Self Web.

Naturally, the Invoice will be considered paid if the ``latest`` Payment is SUCCESS.

**Comment by zoeself** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
