### ISSUE TITLE
SelfPms.java:44-46: Refactor {@link PagedIterator} into...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-storage#29]
The puzzle `20-08fba80a` from #20 has to be resolved: 

https://github.com/self-xdsd/self-storage/blob/fe4eed8ea25a424dc817925ff523d9ddc5a8148f/src/main/java/com/selfxdsd/storage/SelfPms.java#L44-L46

The puzzle was created by cristianpela on 03-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll work on this

**Comment by amihaiemil** [comment]
paid with transaction id: 1MB48433PP632204L
