### ISSUE TITLE
SelfInvoicedTasks.java:154-156: At the moment, the...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-storage#79]
The puzzle `75-c722ebd5` from #75 has to be resolved: 

https://github.com/self-xdsd/self-storage/blob/615198833c03d40f8cb4e30f738b175e0ce4652d/src/main/java/com/selfxdsd/storage/SelfInvoicedTasks.java#L154-L156

The puzzle was created by @amihaiemil on 18-Jul-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
waiting for self-xdsd/self-core#301

**Comment by amihaiemil** [comment]
waiting for self-xdsd/self-core#313

**Comment by 0pdd** [comment]
The puzzle `75-c722ebd5` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
