### ISSUE TITLE
SelfProjects.java:50-51: Check and fix the usage of...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-storage#98]
The puzzle `96-fd6eeea3` from #96 has to be resolved: 

https://github.com/self-xdsd/self-storage/blob/04476d1285aa548a4caa1690bcb350f0fe15c4ac/src/main/java/com/selfxdsd/storage/SelfProjects.java#L50-L51

The puzzle was created by @amihaiemil on 10-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske I've updated the core version to 0.0.4 and adapted SelfProjects to the new pagination mechanism. However, now I'm not sure what to do with the PagedIterator (is it needed anymore?). Can you please check the iteration logic? :D

**Comment by criske** [comment]
@amihaiemil `PagedIterator` will be removed pretty much - maybe we should mark it as deprecated for now, it's still used in some places.
As for the logic it looks like sql `offset+limit` is not applied on queries :).  I'll write some tests to make sure paging is working as it should.

**Comment by amihaiemil** [comment]
@criske As far as I can tell, the paging mechanism only holds the data about the page (current page, number, size), but the actual paging logic has to be implemented individually in each iterator method :D

**Comment by criske** [comment]
@amihaiemil Damn, you're right, I've forgot about that. :D 
Just thinking if can remove those `skip/limit` operators from filter classes. and just feed them with a stream supplier already paged with `offset/limit` which is faster. 
But that's an issue maybe for later as long as current aproach works :D

**Comment by criske** [comment]
@amihaiemil I've found a bug in `BasePaged`. If new projects are registered the total pages will not reflect that increase.
Lets say we have 2 recods initially
```java
Projects projects = storage.projects().page(new Page(1, 2))
projects.totalPages() // should be 1 and is correct
for(int i = 0, i < 10; i++){
  projects.register(...)
}
projects.totalPages()//should be 6 (1 + 5) pages of size 2... but still returns 1
```
I've shoud have kept the `totalRecords` `Supplier` in the old `ProjectsPaged`  https://github.com/self-xdsd/self-core/pull/345/commits/34192ddf2816c7897e981d53c90c9e297811178d

Should I open PR without that test and then create an issue on `self-core`? Or wait for fix?

**Comment by amihaiemil** [comment]
@criske open an Issue in core about it. Also, BasePage should uave the method ``public int totalRecords()``, otherwise it has to be saved in the child class :D

**Comment by amihaiemil** [comment]
@criske can you then take care of this Issue with the cureent approach? .:D

**Comment by criske** [comment]
> can you then take care of this Issue with the cureent approach? .:D

sure

> open an Issue in core about it. Also, BasePage should uave the method `public int totalRecords()`, otherwise it has to be saved in the child class 

@amihaiemil Maybe I'm wrong, but I don't think we need to expose or especially save `totalRecords`. The database should be our "single source of truth". Any saved snapshots like `totalRecords` in SelfProjects could lead to bad state propagation. Basically pages of SelfProjects should pass `database.jooq().fetchCount()` in order that `totalRecords` from BasePage to be up to date.
Something similar is done in [InMemoryProjects](https://github.com/self-xdsd/self-core/blob/0504426ba8a71524c49b79a5a5fd5c3cbfcd6f83/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java#L76)

And I remembered why I ditched the Supplier of totalRecords. Correct me if I'm wrong but `self-storage` will always be queried by `self-web-controllers` in a "stateless" manner, maybe somethin like:
`/projects` -> `storage.projects().page(Page(1, 50)`
`/projects/activate` -> `storage.projects().register(...) ` -> redirect `/projects`
So yeah it's a bug, but in our use case, we can't catch it :D

**Comment by amihaiemil** [comment]
@criske I see. Ok, let's leave it as it is for now:D

**Comment by 0pdd** [comment]
The puzzle `96-fd6eeea3` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@criske paid with transaction id 71Y544538P410164M

Sorry for the delay, busy week...
